name = "v20251104"
main = "_worker.js"
compatibility_date = "2025-11-04"
keep_vars = true

[env.account1]
kv_namespaces = [
  { binding = "KV", id = "5aae647cc84540558a9a91e164e9164f" }
]

[env.account2]
kv_namespaces = [
  { binding = "KV", id = "4bc64ad943d8435db1b1f8091c2b2be6" }
]